### ISSUE TITLE
Lack of a CONTRIBUTING.md makes it difficult to contribute

### ISSUE THREAD

**Issue by DevShubam** [IIC-Development-Team/IIC#15]
I want to contribute by adding some games and software to the list, but there aren't any guidelines. A guide or a quick tutorial of some sorts would be useful.

**Comment by ShadowGamer3301** [comment]
Yes, we know about this issue and are currently working to implement solution that will be both comfortable to our users and us, administrators. (We will post information on both the website and in releases tab when we finish development)

**Comment by ShadowGamer3301** [comment]
Contributing is now described in "About Us" tab on the website.
